apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello-service
  labels:
    app: k8s-web-hello
spec:
  selector:
    app: k8s-web-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
