name: CI/CD Pipeline (Local Minikube)

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: echo "Add your test command here"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker for Minikube
        run: |
          echo "Ensure Minikube is running locally"
          # Optional: configure to use Minikube's Docker daemon if testing locally
          eval $(minikube docker-env)

      - name: Build Docker image
        run: docker build -t k8s-web-hello:latest .

      - name: Set up kubeconfig for Minikube
        run: |
          mkdir -p $HOME/.kube
          cp ~/.kube/config $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
